baseurl = "https://reshi-rajan.github.io/"
title = "Reshi Rajan"
theme = "hugo-theme-nix"
languageCode = "en-us"
draft = "false"



[params]
  Name = "Reshi Rajan"
  HeaderUsername = "rrajan"
  HeaderHostname = "tamu.edu"
  About = "Howdy! I am Reshi Rajan, a first year PhD student in the [Department of Political Science](https://bush.tamu.edu/pols/) at Texas A&M University's [Bush School of Government](https://bush.tamu.edu/) in College Station, Texas. My research interests are primarily in the intersection of comparative political behavior & institutions — specifically the effects institutional arrangements have on voters — and quantitative methodology — particularly maximum likelihood estimation with spatial and time-series cross-sectional data. I completed my B.A. in [International Affairs](https://spia.uga.edu/) with a minor in [Mathematics](https://www.math.uga.edu/) from the University of Georgia in 2023 as well as my M.A. in [Political Science](https://spia.uga.edu/degree/master-of-arts-ma-in-political-science-international-affairs/). In addition to my research interests in political science, my interests in pure mathematics focus on Number Theory, specifically arithmetic in the Quaternions."
  ProfilePicture = "IMG_20220.jpg"
  GithubID = "reshi-rajan"
  Email = "rrajan@tamu.edu"
  TwitterID = "RRajan01"
[menu]
  [[menu.header]]
    name = "Research"
    weight = 1
    url = "/research"
  [[menu.header]]
    name = "CV"
    weight = 2
    url = "/cv"
  [[menu.header]]
    name = "Teaching"
    weight = 3
    url = "/teaching"