baseurl = "https://reshi-rajan.github.io/"
title = "Reshi Rajan"
theme = "hugo-theme-nix"
languageCode = "en-us"
draft = "false"

[params]
  Name = "Reshi Rajan"
  HeaderUsername = "rrajan"
  HeaderHostname = "tamu.edu"
  About = "Welcome! I am Reshi Rajan, a first year PhD student in the Department of Political Science at Texas A&M University's Bush School of Government in College Station, Texas. I recently graduated from the University of Georgia with a B.A. in International Affairs and a minor in Mathematics and an MA in Political Science in 2023. My research interests are primarily in comparative political behavior and institutions as well as quantiative methodology (maximum likelihood estimation) and formal political theory (spatial voting models). In addition to my research interests in Political Science, I also study Number Theory in my spare time."
  ProfilePicture = "IMG_20220.jpg"
  GithubID = "reshi-rajan"
  Email = "rrajan@tamu.edu"
  TwitterID = "RRajan01"
[menu]
  [[menu.header]]
    name = "Research"
    weight = 1
    url = "/research"
  [[menu.header]]
    name = "CV"
    weight = 2
    url = "/cv"
  [[menu.header]]
    name = "Teaching"
    weight = 3
    url = "/teaching"